# Generated by Django 5.1.4 on 2024-12-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMUSIC_Application', '0008_userprofile_bio_alter_userprofile_user'),
    ]

    operations = [
    ]
