# Generated by Django 5.1.3 on 2024-12-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMUSIC_Application', '0010_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mailid',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
