# Generated by Django 5.1.3 on 2025-01-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMUSIC_Application', '0013_subscriptionplan_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
