"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from unittest.main import MODULE_EXAMPLES
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v_h5(mc@n)5u9e#yu219e)c-u(^_+bx5k0hc4y7(x*!q&=+%+6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'EMUSIC_Application',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 3600  # Session duration, in seconds (optional)


ROOT_URLCONF = 'myproject.urls'
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent  # Path to the root directory

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Include a global templates directory,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
                        'debug': True,  # Enable debugging for templates
        },
    },
]
# Debugging: Print template paths during template loading
import os
print("Template directories:", [os.path.join(BASE_DIR, 'templates')])

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/




# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'  # or '/register/' if you're redirecting to registration
# Redirect to home after successful login
LOGIN_REDIRECT_URL = '/home/'

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Default


import os
print("BASE_DIR:", BASE_DIR)
print("Template directory:", os.path.join(BASE_DIR, 'templates'))
print("SPOTIFY_CLIENT_ID:", os.getenv('SPOTIFY_CLIENT_ID'))


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'myproject/static',  # Ensure this is correct based on your structure
    BASE_DIR / "EMUSIC_Application" / "static",  # App-specific static folder
]

STATICFILES_DIRS = [BASE_DIR / "static"]


STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


LOGIN_URL = '/accounts/login/'  # URL to redirect if user is not logged in
LOGIN_REDIRECT_URL = '/'  # Redirect to home page after login

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
LOGIN_URL = '/'

# In settings.py
LOGOUT_REDIRECT_URL = '/'  # Redirect to home or any URL after logout


AUTH_USER_MODEL = 'EMUSIC_Application.CustomUser'

from decouple import config

SPOTIFY_CLIENT_ID = config('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = config('SPOTIFY_CLIENT_SECRET', default='')


LOGIN_REDIRECT_URL = 'EMUSIC_Application:home'  # Redirect after login
LOGIN_URL = 'EMUSIC_Application:login'  # Login page URL for unauthenticated users

import os
from decouple import config
# Set up email backend for development (or configure a real backend for production)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Correct SMTP server for Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='haripriyakoduru039@gmail.com')

# Admin email address from environment variable
ADMIN_EMAIL = config('ADMIN_EMAIL', default='haripriyakoduru039@gmail.com')

# Security settings
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Spotify API
SOCIAL_AUTH_SPOTIFY_REDIRECT_URI = 'http://localhost:8000/spotify/callback'
SPOTIFY_CLIENT_ID = "eaf9342e70444cbdaaa93bd93cc4c9aa"
SPOTIFY_CLIENT_SECRET = "c41d7fe678ba4001b300a1d2e02d571e"

