# Generated by Django 5.1.3 on 2024-12-28 05:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMUSIC_Application', '0004_genre_description_songcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='date_subscribed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('VIP', 'VIP')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
