# Generated by Django 5.1.3 on 2024-12-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMUSIC_Application', '0006_userfavorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFavorites',
        ),
    ]
